language: scala

# This is only necessary for trying out oraclejdk9, which doesn't yet work on their side
# sudo: false
# dist: trusty

scala:
  - 2.11.12
  - 2.12.7
jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

script:
  - sbt clean coverage test coverageReport package package-doc

after_success:
  - bash <(curl -s https://codecov.io/bash)

# This part of the script doesn't seem to work, actually! I never see any binary releases uploaded to github.
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: "QtQK+MK4yylLKyLV6wDF4uuT9R9i/8OhK7OGC8pKAIzu9wylWGMfFmje3JwD69Ek0yd06h+3xG8OU8rRAfQ+hfCRubXGHKi76zeouvxe8BGpbQ6PSsrnUZV6mmOKFWG2EMhVds+r8vZkV/LcT8+RJ6hZoQWkxrsQ7teiV/Bxm5FYiN3hQJHjbJ5H7jRKBRDnDTI1LbTejpVaNCYq7habYhjSYwHpzfuLrtoE0RZvArAz06ltG8iAgLUZiYGPzv3eVWwhhtsj+dTX+B4p5hvdj5ULeRUdU5+XbBwu6+ZneYI1nDLZCxQiN2LWmqhfBvYSeYsmAOySexueOMIwL/+92mD3EHTNoXs39ZX0DSa8sulLQdq+SCeTc7F2SlpsZVesmDm3Y2cfGC5uhIdj7TeP0XD7ex5sL7Wt7gYrrEjhghxaTbyMZy9KtGHw0YEfSM3n9QbDXPun9mk7YPJs+m1jvTa5cL5kxFWI+Oz3eoFV/tSpmVNfxjTIQLlWcasriotMjIM1JoO/qcAe8eoLefpJnfsZZK3IdBRtPm2Gvv+b4I4ET/td/N5k4cFJqp6++vk6ByE+MnctYsOmeftpNPlLRAfh4Ma3OTg9xbaTXUWV62E39XYb6RRTEj0KfI3wvOounWcYIZdhUnLr8hBkczXO8AsPlOHviYU7fpldut6tCUs="
  file: "core/target/scala-2.12/*core*.jar"
  skip_cleanup: true
  on:
    tags

# See https://gist.github.com/estliberitas/b2c004f7447ed6fa3248
# Use following configuration to run ZooKeeper while executing tests

before_install:
## Add repository key
#- "curl -s http://archive.cloudera.com/cdh4/ubuntu/precise/amd64/cdh/archive.key | sudo apt-key add -"
- "curl -s http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/archive.key | sudo apt-key add -"
#- "wget http://archive.cloudera.com/cdh4/one-click-install/precise/amd64/cdh4-repository_1.0_all.deb"
#- "wget https://archive.cloudera.com/cdh5/one-click-install/trusty/amd64/cdh5-repository_1.0_all.deb"
#- "sudo dpkg -i cdh5-repository_1.0_all.deb"
#- "sudo wget https://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/cloudera.list -O /etc/apt/sources.list.d/cloudera.list"
- "sudo echo 'deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh trusty-cdh5 contrib' > cloudera.list"
- "sudo mv cloudera.list /etc/apt/sources.list.d/cloudera.list"
- "sudo echo -e 'Package: *\\nPin: release o=Cloudera, l=Cloudera\\nPin-Priority: 501' > cloudera.pref"
- "cat cloudera.pref"
- "sudo mv cloudera.pref /etc/apt/preferences.d/cloudera.pref"
- "sudo apt-get update -qq"
# Install ZooKeeper
- "sudo apt-get install -y zookeeper-server"
before_script:
- "sudo service zookeeper-server init"
- "sudo service zookeeper-server start"
after_script:
- "sudo service zookeeper-server stop"
